/* ==========================================================================
   Themes — visual + terminological reskins of the core product
   ========================================================================== */

export const THEMES = {
  court: {
    name: 'Court',
    tagline: 'Legal / Editorial',
    description: 'Adversarial court of moral reasoning.',
    labels: {
      // Product-level framing
      session: 'Session',
      code: 'Legal code',
      codeShort: 'Code',
      round: 'Round',
      runRound: 'Run round',
      running: 'Running...',
      rule: 'Ruling',
      cases: 'Cases',
      case: 'Case',
      needsYou: 'Needs your ruling',
      yourRuling: 'Your ruling',
      ruledBy: 'decided by you',
      autoResolved: 'resolved automatically',
      judgeWillFix: 'Judge will fix it',
      needsYouShort: 'Needs your ruling',
      submitRuling: 'Submit ruling',
      suggestFix: '+ suggest a fix',
      suggestPlaceholder: 'How would you fix the code to prevent this?',
      rulingPlaceholder: 'How should this be handled? Your answer becomes a permanent rule.',
      escalationBanner: 'Your ruling needed.',
      escalationReason: "The judge can't resolve this without contradicting a past decision.",
      ready: 'Ready',
      drafting: 'Writing code...',
      searching: 'Finding attacks...',
      judging: 'Judge thinking...',
      escalated: 'Needs your ruling',
      panelTitle: 'Legal code',
      panelSubtitle: 'Drafted from your principles, revised as cases arrive',
      docketTitle: 'Cases',
      docketSubtitle: "Attacks on the legal code, as they're found",
      emptyTitle: 'No cases yet',
      emptyDesc: "Run a round to have AI agents attack the current legal code. They'll find loopholes (legal but immoral) and overreach (illegal but moral).",
      runFirst: 'Run first round',
      resolution: 'Resolution',
    },
  },

  terminal: {
    name: 'Terminal',
    tagline: 'Red-team / Security',
    description: 'Adversarial testing of policy as code.',
    labels: {
      session: 'Run',
      code: 'Ruleset',
      codeShort: 'Ruleset',
      round: 'Cycle',
      runRound: 'Start cycle',
      running: 'running...',
      rule: 'Patch',
      cases: 'Findings',
      case: 'Finding',
      needsYou: 'Needs your patch',
      yourRuling: 'Your patch',
      ruledBy: 'patched by you',
      autoResolved: 'auto-patched',
      judgeWillFix: 'Auto-patch will handle it',
      needsYouShort: 'need patch',
      submitRuling: 'Apply patch',
      suggestFix: '+ propose patch',
      suggestPlaceholder: 'Propose a patch to close this hole.',
      rulingPlaceholder: 'Write the patch. It becomes a permanent rule.',
      escalationBanner: 'Manual patch required.',
      escalationReason: 'Auto-patcher cannot resolve without breaking prior constraints.',
      ready: 'idle',
      drafting: 'compiling ruleset...',
      searching: 'running exploits...',
      judging: 'evaluating...',
      escalated: 'manual patch required',
      panelTitle: 'Ruleset',
      panelSubtitle: 'Compiled from your spec, patched per finding',
      docketTitle: 'Findings',
      docketSubtitle: 'Exploits + false positives, as discovered',
      emptyTitle: '> no findings',
      emptyDesc: 'Start a cycle to run adversarial agents. They find exploits (rule says yes but you say no) and false positives (rule says no but you say yes).',
      runFirst: 'Start first cycle',
      resolution: 'Patch',
    },
  },

  lab: {
    name: 'Lab',
    tagline: 'Clinical / Research',
    description: 'Falsification testing of a moral policy.',
    labels: {
      session: 'Experiment',
      code: 'Policy',
      codeShort: 'Policy',
      round: 'Trial',
      runRound: 'Run trial',
      running: 'Running...',
      rule: 'Revision',
      cases: 'Observations',
      case: 'Observation',
      needsYou: 'Needs your decision',
      yourRuling: 'Your decision',
      ruledBy: 'decided by you',
      autoResolved: 'auto-revised',
      judgeWillFix: 'Reviewer will revise it',
      needsYouShort: 'need decision',
      submitRuling: 'Submit decision',
      suggestFix: '+ propose revision',
      suggestPlaceholder: 'Propose a revision to the policy that addresses this.',
      rulingPlaceholder: 'How should this be handled? Your decision becomes a permanent constraint.',
      escalationBanner: 'Your decision required.',
      escalationReason: 'The reviewer cannot revise without contradicting a prior decision.',
      ready: 'Idle',
      drafting: 'Drafting policy...',
      searching: 'Running probes...',
      judging: 'Reviewer analyzing...',
      escalated: 'Decision required',
      panelTitle: 'Policy',
      panelSubtitle: 'Drafted from principles, revised per finding',
      docketTitle: 'Observations',
      docketSubtitle: 'Probes that falsify the policy, as found',
      emptyTitle: 'No observations',
      emptyDesc: 'Run a trial to have adversarial probes test the policy. They find over-permits (policy allows what you would not) and over-prohibits (policy forbids what you would allow).',
      runFirst: 'Run first trial',
      resolution: 'Revision',
    },
  },
};

export const DEFAULT_THEME = 'court';

export function getTheme(key) {
  return THEMES[key] || THEMES[DEFAULT_THEME];
}
